package mu.sic;

import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class signup extends javax.swing.JFrame {
    
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public signup() {
        setResizable(false); // Disable resizing of the JFrame
        setTitle("Signup Page");
        
        // Set the icon image for the JFrame
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/IconApp.png"));
        setIconImage(icon.getImage());
        initComponents();
        setSize(600, 500); // Set the size of the JFrame to match your design
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    }
    
    public void bersih(){
       usernameJF.setText("");
       nohpJF.setText("");
       emailJF.setText("");
       passwordJF.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        passwordJF = new javax.swing.JPasswordField();
        emailJF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernameJF = new javax.swing.JTextField();
        nohpJF = new javax.swing.JTextField();
        Logo = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJFActionPerformed(evt);
            }
        });
        jPanel2.add(passwordJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 137, 120, -1));
        jPanel2.add(emailJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 171, 120, -1));

        jLabel1.setText("Username :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 109, -1, -1));

        jLabel2.setText("Password :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 143, -1, -1));

        jLabel4.setText("Email :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 177, -1, -1));

        jLabel5.setText("No.hp :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 211, -1, -1));
        jPanel2.add(usernameJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 106, 120, -1));
        jPanel2.add(nohpJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 205, 120, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        Logo.setText("jLabel2");
        jPanel2.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 44, 160, -1));

        signup.setBackground(new java.awt.Color(0, 0, 0));
        signup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("SIGN UP");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        jPanel2.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        login.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        login.setForeground(new java.awt.Color(0, 153, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 268, 64, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setText("Already have an account?");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 267, 121, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 460));

        setSize(new java.awt.Dimension(616, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordJFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJFActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        String username = usernameJF.getText();
        String email = emailJF.getText();
        String nohp = nohpJF.getText();
        String password = String.valueOf(passwordJF.getPassword());
        
         
        // Make Sure User Input not Blank
        if (username.isEmpty() || email.isEmpty() || password.isEmpty() || nohp.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh ada yang kosong");
            return;
        }
        
        try {
            sql = "SELECT * FROM login";
            rs = stat.executeQuery(sql);
            boolean check = false;
            
            // Looping Check / Row on database
            while(rs.next()) {
                // Check if username is same on database
                if(username.equals(rs.getString("username")) ){
                    JOptionPane.showMessageDialog(null,"Username sudah terdaftar");
                    check = true;
                    bersih();
                }
            }
            
            if(check == false){
                sql = "INSERT INTO login VALUES ('"
                    + username + "','"
                    + password + "','" 
                    + email + "','" 
                    + nohp + "'," 
                    + "0,0,0)";
                stat.executeUpdate(sql);
                {
                    JOptionPane.showMessageDialog(null,"Registrasi Berhasil!\nHarap Login kembali");
                    new login().setVisible(true);
                    this.setVisible(false);
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            bersih();
        }
    }//GEN-LAST:event_signupActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // Make signup frame opened in center
        login frame = new login();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        frame.pack();
        frame.setLocationRelativeTo(null);
        this.dispose();

        // Make this frame (login) dissapear
        this.setVisible(false);
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                signup frame = new signup();
                frame.setLocationRelativeTo(null); // Center the JFrame on the screen
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField emailJF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JTextField nohpJF;
    private javax.swing.JPasswordField passwordJF;
    private javax.swing.JButton signup;
    private javax.swing.JTextField usernameJF;
    // End of variables declaration//GEN-END:variables
}
